### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by WouldChar** [DreaminginCodeZH/android_device_zte_nx510j#3]
你好，我用你的源码编译了lineage14.1，但是编译出来的内核无法开机，请问这个问题该怎么解决？

**Comment by DreaminginCodeZH** [comment]
没有解决，正在尝试。

**Comment by DreaminginCodeZH** [comment]
你可以试试 https://github.com/DreaminginCodeZH/android_device_zte_nx510j-1 ，别人适配的。我猜可能是 N 的 init.rc 变了？

**Comment by WouldChar** [comment]
我提取了mokee里的init文件改了device然后编译，内核可以开机，但是刚进设置向导就重启了，是不是selinux有问题？

**Comment by WouldChar** [comment]
已解决。

**Comment by DreaminginCodeZH** [comment]
你好，我尝试用了一下你的 deivce repo 进行 build，遇到了这个问题：

```
ninja: error: 'device/zte/nx510j/gps/etc/izat.lowi', needed by '/home/zh/lineage/out/target/product/nx510j/system/etc/lowi.conf', missing and no known
 rule to make it
```

请问你是怎么解决的？

**Comment by WouldChar** [comment]
我编译的时候没有出现。你看一下gps/etc文件夹有没有缺文件，或者product里面的gps mk文件代码有没有跟我的不一样的。

**Comment by DreaminginCodeZH** [comment]
我把 [product/qcom-gps.mk#L8](https://github.com/WouldChar/android_device_zte_nx510j/blob/cm-14.1/product/qcom-gps.mk#L8) 从 `izat.lowi` 改成了 `lowi.conf`，编译开始了；感觉是 typo？

**Comment by WouldChar** [comment]
现在用起来还正常，没什么大的问题。我卡是移动的，电信和联通的没测试过。

**Comment by DreaminginCodeZH** [comment]
@WouldChar 你刷机时遇到了 updater-script status 6 么？我之前自己的 build 没有遇到过。我使用的是 TWRP 3.0.0

**Comment by WouldChar** [comment]
你得把vendor/zte/nx510j/Android.mk下
ifeq ($(LOCAL_PATH)/radio, $(wildcard $(LOCAL_PATH)/radio))…那段代码去掉，还有之前那个device tree代码的audio有问题，声音不能外放，你需要同步最新的device tree。
